Data <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", 
                 nrows=2075259)
Data_Date <- subset(Data, Date %in% c("1/2/2007", "2/2/2007"))
Data_Date$Date <- as.Date(Data_Date$Date, "%d/%m/%y")
Datetime <- paste(as.Date(Data_Date$Date), Data_Date$Time)
Data_Date$Datetime <- as.POSIXct(Datetime)
with(Data_Date, {plot(Sub_metering_1 ~ Datetime, type = "l", ylab = "Energy sub metering", xlab = "")
  lines(Sub_metering_2 ~ Datetime, col = "red")
  lines(Sub_metering_3 ~ Datetime, col = "blue")})
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, "plot3.png", width = 480, height = 480)
dev.off()